### ISSUE TITLE
Review

### ISSUE THREAD

**Issue by eaedk** [aliduabubakari/Streamlit-grocery-sales-prediction-app#1]
Rectify the links in the "Summary section"
Format the commands in the "Install the dependencies" to enable copy-paste option
Add commands in the "App Execution section"

Good job

**Comment by eaedk** [comment]
Create folders to organize your repo

**Comment by aliduabubakari** [comment]
I would like to close this issue. Please advice

**Comment by eaedk** [comment]
good work
